### ISSUE TITLE
Getting logged out after 15m

### ISSUE THREAD

**Issue by MaxHayman** [paul999/phpbb_2fa#14]
Hello,

I seem to be getting logged out every ~15m. I have remember me set.

Having to log in and enter authenticator code every 15m is quite annoying.

Any idea what it could be?

**Comment by paul999** [comment]
Please post your support questions at https://www.phpbb.com/community/viewtopic.php?f=456&t=2341856

**Comment by paul999** [comment]
Can you try if the changes from #17 fixes it?

**Comment by MaxHayman** [comment]
Yes it is fixed in the latest release thanks.
